/* tslint:disable */
/* eslint-disable */
/**
 * 簡易物品管理WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Usage,
    UsageFromJSON,
    UsageToJSON,
} from '../models';

export interface GetUsageistRequest {
    userId?: number;
}

/**
 * 
 */
export class UsageApi extends runtime.BaseAPI {

    /**
     * 使用状況情報の一覧を取得します。
     * 使用状況情報一覧取得
     */
    async getUsageistRaw(requestParameters: GetUsageistRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Usage>>> {
        const queryParameters: any = {};

        if (requestParameters.userId !== undefined) {
            queryParameters['userId'] = requestParameters.userId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/usages`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UsageFromJSON));
    }

    /**
     * 使用状況情報の一覧を取得します。
     * 使用状況情報一覧取得
     */
    async getUsageist(requestParameters: GetUsageistRequest, initOverrides?: RequestInit): Promise<Array<Usage>> {
        const response = await this.getUsageistRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
