version: '3.1'

services:

  app:
    build: ./
    stdin_open: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/workspace
    ports:
      - 8080:8080
      - 5001:5001
    depends_on:
      - db

  db:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_DB: simple
      POSTGRES_USER: simple
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4:4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dummy.com
      PGADMIN_DEFAULT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - admin-db:/var/lib/pgadmin
    ports:
      - 8000:80

volumes:
  postgres-db:
    driver: local
  admin-db:
    driver: local