# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from simple_item_manager.models.base_model_ import Model
from simple_item_manager import util


class Footprint(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, created_at=None, created_by=None, updated_at=None, updated_by=None):  # noqa: E501
        """Footprint - a model defined in OpenAPI

        :param created_at: The created_at of this Footprint.  # noqa: E501
        :type created_at: datetime
        :param created_by: The created_by of this Footprint.  # noqa: E501
        :type created_by: str
        :param updated_at: The updated_at of this Footprint.  # noqa: E501
        :type updated_at: datetime
        :param updated_by: The updated_by of this Footprint.  # noqa: E501
        :type updated_by: str
        """
        self.openapi_types = {
            'created_at': datetime,
            'created_by': str,
            'updated_at': datetime,
            'updated_by': str
        }

        self.attribute_map = {
            'created_at': 'createdAt',
            'created_by': 'createdBy',
            'updated_at': 'updatedAt',
            'updated_by': 'updatedBy'
        }

        self._created_at = created_at
        self._created_by = created_by
        self._updated_at = updated_at
        self._updated_by = updated_by

    @classmethod
    def from_dict(cls, dikt) -> 'Footprint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Footprint of this Footprint.  # noqa: E501
        :rtype: Footprint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self):
        """Gets the created_at of this Footprint.

        作成日時  # noqa: E501

        :return: The created_at of this Footprint.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Footprint.

        作成日時  # noqa: E501

        :param created_at: The created_at of this Footprint.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this Footprint.

        作成者ID  # noqa: E501

        :return: The created_by of this Footprint.
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this Footprint.

        作成者ID  # noqa: E501

        :param created_by: The created_by of this Footprint.
        :type created_by: str
        """

        self._created_by = created_by

    @property
    def updated_at(self):
        """Gets the updated_at of this Footprint.

        更新日時  # noqa: E501

        :return: The updated_at of this Footprint.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this Footprint.

        更新日時  # noqa: E501

        :param updated_at: The updated_at of this Footprint.
        :type updated_at: datetime
        """

        self._updated_at = updated_at

    @property
    def updated_by(self):
        """Gets the updated_by of this Footprint.

        更新者ID  # noqa: E501

        :return: The updated_by of this Footprint.
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this Footprint.

        更新者ID  # noqa: E501

        :param updated_by: The updated_by of this Footprint.
        :type updated_by: str
        """

        self._updated_by = updated_by
