# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from simple_item_manager.models.base_model_ import Model
from simple_item_manager import util


class InlineObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nfc_serial_no=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI

        :param nfc_serial_no: The nfc_serial_no of this InlineObject.  # noqa: E501
        :type nfc_serial_no: str
        """
        self.openapi_types = {
            'nfc_serial_no': str
        }

        self.attribute_map = {
            'nfc_serial_no': 'nfcSerialNo'
        }

        self._nfc_serial_no = nfc_serial_no

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object of this InlineObject.  # noqa: E501
        :rtype: InlineObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nfc_serial_no(self):
        """Gets the nfc_serial_no of this InlineObject.

        NFCタグのシリアル番号  # noqa: E501

        :return: The nfc_serial_no of this InlineObject.
        :rtype: str
        """
        return self._nfc_serial_no

    @nfc_serial_no.setter
    def nfc_serial_no(self, nfc_serial_no):
        """Sets the nfc_serial_no of this InlineObject.

        NFCタグのシリアル番号  # noqa: E501

        :param nfc_serial_no: The nfc_serial_no of this InlineObject.
        :type nfc_serial_no: str
        """

        self._nfc_serial_no = nfc_serial_no
